### ISSUE TITLE
你好，希望联系你

### ISSUE THREAD

**Issue by zhuewizz** [LKKlein/paddleocr-go#2]
我加你的QQ:1172977438了，有事咨询你

**Comment by LKKlein** [comment]
> 我加你的QQ:1172977438了，有事咨询你

下次记得先大概备注一下具体事情，白天工作比较忙，一般非急事不会处理的哈

**Comment by suifengqjn** [comment]
作者大佬为啥不直接放一个编译好的包，或者打个docker

**Comment by LKKlein** [comment]
> 

之前忘记了，最近看看时间有空的话可以考虑搞一个
